/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Cat = React.memo(function Cat(props) {

  const { nodes, materials } = useGLTF('models/tootsy_roll_cat_25th_may_2020.glb')
  const modelRef = useRef();
  const modelRef1 = useRef();
  const modelRef3 = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  useFrame(() => {
    modelRef1.current.rotation.y -= 0.005;
  });
  useFrame((state) => {

    modelRef3.current.rotation.y =
      Math.sin(state.clock.elapsedTime) * 0.5;
  });
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2.5, 0, 0.7]} scale={[0.7, 0.7, 0.7]}>
        <mesh

          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_14}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.material_12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.material_11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.material_10}
        />



        <group ref={modelRef3}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.material_9}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.material_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials.material_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.material_6}
        />


        <group ref={modelRef1} position={[1, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials.material_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials.material_5}
          />
        </group>



        <group ref={modelRef}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials.material_5}
          />


          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.material_2}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials.material_12}
        />
      </group>
    </group>
  );
});

export default Cat;
useGLTF.preload('models/tootsy_roll_cat_25th_may_2020.glb')
